name: Run auto_lotto_main.py Daily

# Define triggers: scheduled and manual
on:
  schedule:
    # Runs daily at 00:00 UTC
    - cron: '0 0 * * *'
  workflow_dispatch:
  push:
    branches:
      - main


jobs:
  run-auto-lotto:
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9.16' # Adjust to the version your script requires

      - name: Install Dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run auto_lotto_main.py
        run: python auto_lotto_main.py